server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
  address: 127.0.0.1

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3309/social?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

    properties:
      hibernate:
        default_batch_fetch_size: 50
        format_sql: true
        highlight_sql: true


  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  security:
    user:
      name: test
      password: 1234
    # OAUth2
    oauth2:
      client:
        registration:
          facebook:
            client-id: example
            client-secret: example
            scope:
              - public_profile
              - email

          google:
            client-id: example
            client-secret: example
            scope:
              - email
              - profile

file:
  path: C:/social/springbootwork/upload/

logging:
  level:
    org:
      springframework:
        security: DEBUG

